CC = gcc

SRC = hash.c main.c list.c node_list.c node_tree.c vector.c binary_tree.c
OUT = main

CFLAGS = -pedantic -Wall -Wextra -Wwrite-strings -g3

all :
	$(CC) $(SRC) -o $(OUT) $(IFLAGS) $(CFLAGS)
	
clean :
	rm *.o