CC = gcc

SRC = main.c vector.c heap.c deque.c 
OUT = trabalho1

CFLAGS = -pedantic -Wall -Wextra -Wwrite-strings -g3

all :
	$(CC) $(SRC) -o $(OUT) $(CFLAGS)
	
clean :
	rm *.o

#gcc main.c vector.c heap.c deque.c -o trabalho1 -pedantic -Wall -Wextra -Wwrite-strings -g3